# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XCframeworkDemoPod' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
use_modular_headers!

 pod 'StaticLibrary/Code', :git => 'https://github.com/fanlilinSaber/xcframework_study.git'

  # Pods for XCframeworkDemoPod

end
