# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StaticLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'

  # Pods for StaticLibrary

end

target 'StaticLibrary IOS Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StaticLibrary IOS Example

end
